=== fabienbk/SpringBatchExample/src/main/resources/GRD_R04.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="Index_C5" type="Index_C5"/>
	<xsd:complexType name="Index_C5" mixed="false">
		<xsd:sequence>
			<xsd:element name="Entete" type="Entete"/>
			<xsd:element name="Corps_de_fichier_par_PDL" type="Corps_de_fichier_par_PDL" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Entete" mixed="false">
		<xsd:sequence>
			<xsd:element name="Identifiant_Flux">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="20"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Libelle_Flux">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="250"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Identifiant_Emetteur">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="20"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Coordonnees_Emetteur" type="Coordonnees_Emetteur"/>
			<xsd:element name="Identifiant_Destinataire">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="20"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Coordonnees_Destinataire" type="Coordonnees_Destinataire"/>
			<xsd:element name="Date_Version_Message" type="xsd:date" minOccurs="0"/>
			<xsd:element name="Date_Creation" type="xsd:dateTime"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Coordonnees_Emetteur" mixed="false">
		<xsd:sequence>
			<xsd:element name="Coordonnees_E_Ligne1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="38"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Coordonnees_E_Ligne2" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="38"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Coordonnees_E_Ligne3" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="38"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Coordonnees_E_Ligne4" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="38"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Coordonnees_E_Ligne5" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="38"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Coordonnees_E_Ligne6" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="38"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Coordonnees_E_Ligne7" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="38"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Coordonnees_Destinataire" mixed="false">
		<xsd:sequence>
			<xsd:element name="Coordonnees_D_Ligne1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="38"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Coordonnees_D_Ligne2" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="38"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Coordonnees_D_Ligne3" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="38"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Coordonnees_D_Ligne4" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="38"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Coordonnees_D_Ligne5" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="38"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Coordonnees_D_Ligne6" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="38"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Coordonnees_D_Ligne7" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="38"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Corps_de_fichier_par_PDL" mixed="false">
		<xsd:sequence>
			<xsd:element name="Identifiant_Stable_PDL">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="14"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Rang_QE">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Type_Client" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Type_Relation_Contractuelle">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Evenement_Declencheur">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Numero_Telephone_Depannage_Urgence">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="20"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Facture_Deroutee" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Source_Redressement" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Motif_Redressement" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Commentaire_Redressement" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="100"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Date_Theorique_Prochaine_Releve" type="xsd:date" minOccurs="0"/>
			<xsd:element name="Situation_Contrat" type="Situation_Contrat" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Situation_Contrat" mixed="false">
		<xsd:sequence>
			<xsd:element name="Identifiant_Responsable_Equilibre">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="2"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Code_Tarif">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="4"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Identifiant_Situation">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="3"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Mode_Redressement">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Type_Redressement" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Code_Calcul_Tarif" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="2"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Date_Debut_Consommation" type="xsd:date" minOccurs="0"/>
			<xsd:element name="Date_Fin_Consommation" type="xsd:date" minOccurs="0"/>
			<xsd:element name="Libelle_Plage_Heures_Creuses" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="33"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Compteur" type="Compteur"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Compteur" mixed="false">
		<xsd:sequence>
			<xsd:element name="Matricule_Compteur">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="3"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Nombre_Cadrans">
				<xsd:simpleType>
					<xsd:restriction base="xsd:positiveInteger">
						<xsd:totalDigits value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Periode" type="Periode" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Periode" mixed="false">
		<xsd:sequence>
			<xsd:element name="Indicateur_De_Periode">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Puissance_Souscrite">
				<xsd:simpleType>
					<xsd:restriction base="xsd:positiveInteger">
						<xsd:totalDigits value="5"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Donnees_Cadran" type="Donnees_Cadran" maxOccurs="2"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Donnees_Cadran" mixed="false">
		<xsd:sequence>
			<xsd:element name="Rang_Cadran">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Nature_Index_Debut" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Processus_Index_Debut" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Index_Debut_Consommation" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:nonNegativeInteger">
						<xsd:totalDigits value="7"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Origine_Index_Debut" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Indicateur_Passage_A_Zero" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Nature_Index_A_Facturer" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Processus_Index_A_Facturer" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Index_A_Facturer" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:nonNegativeInteger">
						<xsd:totalDigits value="7"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Origine_Index_A_Facturer" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:length value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Consommation_Cadran" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:int">
						<xsd:totalDigits value="8"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== fabienbk/SpringBatchExample/src/main/resources/GRD_R041.xml
<?xml version="1.0" encoding="UTF-8"?>
<Index_C5 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GRD_R04.xsd">
  <Entete>
    <Identifiant_Flux>Identifiant_Flux</Identifiant_Flux>
    <Libelle_Flux>Libelle_Flux</Libelle_Flux>
    <Identifiant_Emetteur>Identifiant_Emetteur</Identifiant_Emetteur>
    <Coordonnees_Emetteur>
      <Coordonnees_E_Ligne1>Coordonnees_E_Ligne1</Coordonnees_E_Ligne1>
    </Coordonnees_Emetteur>
    <Identifiant_Destinataire>Identifiant_Destinataire</Identifiant_Destinataire>
    <Coordonnees_Destinataire>
      <Coordonnees_D_Ligne1>Coordonnees_D_Ligne1</Coordonnees_D_Ligne1>
    </Coordonnees_Destinataire>
    <Date_Version_Message>2001-01-01</Date_Version_Message>
    <Date_Creation>2001-12-31T12:00:00</Date_Creation>
  </Entete>
  <Corps_de_fichier_par_PDL>
    <Identifiant_Stable_PDL>Identifiant_Stable_PDL</Identifiant_Stable_PDL>
    <Rang_QE>Rang_QE</Rang_QE>
    <Type_Client>Type_Client</Type_Client>
    <Type_Relation_Contractuelle>Type_Relation_Contractuelle</Type_Relation_Contractuelle>
    <Evenement_Declencheur>Evenement_Declencheur</Evenement_Declencheur>
    <Numero_Telephone_Depannage_Urgence>Numero_Telephone_Depannage_Urgence</Numero_Telephone_Depannage_Urgence>
    <Facture_Deroutee>Facture_Deroutee</Facture_Deroutee>
    <Source_Redressement>Source_Redressement</Source_Redressement>
    <Motif_Redressement>Motif_Redressement</Motif_Redressement>
    <Commentaire_Redressement>Commentaire_Redressement</Commentaire_Redressement>
    <Date_Theorique_Prochaine_Releve>2001-01-01</Date_Theorique_Prochaine_Releve>
    <Situation_Contrat>
      <Identifiant_Responsable_Equilibre>Identifiant_Responsable_Equilibre</Identifiant_Responsable_Equilibre>
      <Code_Tarif>Code_Tarif</Code_Tarif>
      <Identifiant_Situation>Identifiant_Situation</Identifiant_Situation>
      <Mode_Redressement>Mode_Redressement</Mode_Redressement>
      <Compteur>
        <Matricule_Compteur>Matricule_Compteur</Matricule_Compteur>
        <Nombre_Cadrans>1</Nombre_Cadrans>
        <Periode>
          <Indicateur_De_Periode>Indicateur_De_Periode</Indicateur_De_Periode>
          <Puissance_Souscrite>1</Puissance_Souscrite>
          <Donnees_Cadran>
            <Rang_Cadran>Rang_Cadran</Rang_Cadran>
          </Donnees_Cadran>
        </Periode>
      </Compteur>
    </Situation_Contrat>
  </Corps_de_fichier_par_PDL>
</Index_C5>
